### ISSUE TITLE
Failed to run script

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [anyblockanalytics/thegraph-allocation-optimization#2]
Using latest commit from master. I have error:
```
python3 ./allocation_script.py --indexer_id 0x453b5e165cf98ff60167ccd3560ebf8d436ca86c --max_percentage 0.9 --threshold 20 --parallel_allocations 4 --no-subgraph-list
Script Execution on:  10062021_17:18:58
                                                                                           Name_x  \
Name_y                 Address
Opyn Gamma Mainnet     0x014e8a3184d5fad198123419a7b54d5f7c9f8a9811164...      Opyn Gamma Mainnet
UMA Mainnet Voting     0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996...      UMA Mainnet Voting
PoolTogether           0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d6...            PoolTogether
Omen                   0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e...                    Omen
NaN                    0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e7...                       0
PoolTogether v3_1_0    0x4a008334f8e7ea21be223d15462084f51abcc0e6625f6...     PoolTogether v3_1_0
Audius Network Mainnet 0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef...  Audius Network Mainnet
DODOEX V2              0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653...               DODOEX V2
PoolTogether           0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e...            PoolTogether
mStable Protocol       0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfd...        mStable Protocol
PoolTogether           0xbae01a063ad846d7e4200757480544b5feb1f0217d94d...            PoolTogether
                       0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e6...            PoolTogether
NaN                    0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f...                       0
RAI Mainnet            0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94...             RAI Mainnet
NaN                    0xf8481d0118ec6098d00629414d600f5d87a1c8a94e272...                       0

                                                                           Allocation  \
Name_y                 Address
Opyn Gamma Mainnet     0x014e8a3184d5fad198123419a7b54d5f7c9f8a9811164...     1000.00
UMA Mainnet Voting     0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996...     1000.00
PoolTogether           0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d6...     1000.00
Omen                   0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e...     1520.00
NaN                    0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e7...        0.00
PoolTogether v3_1_0    0x4a008334f8e7ea21be223d15462084f51abcc0e6625f6...     1000.00
Audius Network Mainnet 0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef...  2094523.81
DODOEX V2              0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653...     1000.00
PoolTogether           0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e...     1000.00
mStable Protocol       0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfd...     1000.00
PoolTogether           0xbae01a063ad846d7e4200757480544b5feb1f0217d94d...     1520.00
                       0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e6...     1000.00
NaN                    0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f...        0.00
RAI Mainnet            0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94...     1000.00
NaN                    0xf8481d0118ec6098d00629414d600f5d87a1c8a94e272...        0.00

                                                                           signalledTokensTotal  \
Name_y                 Address
Opyn Gamma Mainnet     0x014e8a3184d5fad198123419a7b54d5f7c9f8a9811164...          1.114358e+05
UMA Mainnet Voting     0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996...          1.107550e+05
PoolTogether           0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d6...          1.044858e+06
Omen                   0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e...          1.094111e+05
NaN                    0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e7...          1.071212e+05
PoolTogether v3_1_0    0x4a008334f8e7ea21be223d15462084f51abcc0e6625f6...          1.020313e+05
Audius Network Mainnet 0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef...          3.325000e+03
DODOEX V2              0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653...          1.195504e+05
PoolTogether           0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e...          4.609030e+03
mStable Protocol       0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfd...          1.207112e+05
PoolTogether           0xbae01a063ad846d7e4200757480544b5feb1f0217d94d...          3.325250e+03
                       0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e6...          1.097212e+05
NaN                    0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f...          1.079020e+05
RAI Mainnet            0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94...          5.575000e+03
NaN                    0xf8481d0118ec6098d00629414d600f5d87a1c8a94e272...          1.159212e+05

                                                                           stakedTokensTotal  \
Name_y                 Address
Opyn Gamma Mainnet     0x014e8a3184d5fad198123419a7b54d5f7c9f8a9811164...       1.263166e+08
UMA Mainnet Voting     0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996...       1.036077e+08
PoolTogether           0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d6...       1.026075e+09
Omen                   0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e...       1.301232e+08
NaN                    0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e7...       1.066076e+08
PoolTogether v3_1_0    0x4a008334f8e7ea21be223d15462084f51abcc0e6625f6...       1.037022e+08
Audius Network Mainnet 0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef...       5.554902e+07
DODOEX V2              0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653...       1.088510e+08
PoolTogether           0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e...       2.000020e+03
mStable Protocol       0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfd...       1.372995e+08
PoolTogether           0xbae01a063ad846d7e4200757480544b5feb1f0217d94d...       2.817701e+05
                       0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e6...       1.613664e+08
NaN                    0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f...       1.300212e+08
RAI Mainnet            0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94...       5.345775e+07
NaN                    0xf8481d0118ec6098d00629414d600f5d87a1c8a94e272...       7.501863e+07

                                                                                                                       id
Name_y                 Address
Opyn Gamma Mainnet     0x014e8a3184d5fad198123419a7b54d5f7c9f8a9811164...  QmNRkaVUwUQAwPwWgdQHYvw53A5gh3CP3giWnWQZdA2BTE
UMA Mainnet Voting     0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996...  QmRDGLp6BHwiH9HAE2NYEE3f7LrKuRqziHBv76trT4etgU
PoolTogether           0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d6...  QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF
Omen                   0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e...  QmRhh7rFt3qxfRMTZvHRNK6jCobX4Gx5TkzWXhZkuj57w8
NaN                    0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e7...  QmTBxvMF6YnbT1eYeRx9XQpH4WvxTV53vdptCCZFiZSprg
PoolTogether v3_1_0    0x4a008334f8e7ea21be223d15462084f51abcc0e6625f6...  QmTKXLEdMD6Vq7Nwxo8XAfnHpG6H1TzL1AGwiqLpoae3Pb
Audius Network Mainnet 0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef...  QmTj6fHgHjuKKm43YL3Sm2hMvMci4AkFzx22Mdo9W3dyn8
DODOEX V2              0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653...  QmUghXvKf5cVjtayNNRHCd3RbHEwfbGBQ95s9vheJjN5hH
PoolTogether           0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e...  QmVEV7RA2U6BJT9Ssjxcfyrk4YQUnVqSRNX4TvYagjzh9h
mStable Protocol       0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfd...  QmZdsSbRwVD7VVVm5WGxZZC6HYvbjnFb4hcwvQ4fTs5bxA
PoolTogether           0xbae01a063ad846d7e4200757480544b5feb1f0217d94d...  Qmav8jkmAeKBLyxmngJVwprN3ZsJA9A57jeoikdCU2Dyrv
                       0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e6...  Qmaz1R8vcv9v3gUfksqiS9JUz7K9G8S5By3JYn8kTiiP5K
NaN                    0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f...  QmbHg6vAJRD9ZWz5GTP9oMrfDyetnGTr5KWJBYAq59fm1W
RAI Mainnet            0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94...  QmbYFfUKETrUwTQ7z8VD87KFoYJps8TGsSbM6m8bi6TaKG
NaN                    0xf8481d0118ec6098d00629414d600f5d87a1c8a94e272...  Qmf3qbX2SF58ifUQfMvWJKe99g9DavSKtRxm3evvCHocwS
==============================
Indexing Reward Daily per Subgraph:
[('Opyn Gamma Mainnet', '0x014e8a3184d5fad198123419a7b54d5f7c9f8a981116462591fbb1a922c39811')
 ('UMA Mainnet Voting', '0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996238adc2bfd396b5f715')
 ('PoolTogether', '0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500')
 ('Omen', '0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e97a1402795c0c2fa99b')
 (nan, '0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e74b6186d3a2264588fe5')
 ('PoolTogether v3_1_0', '0x4a008334f8e7ea21be223d15462084f51abcc0e6625f61de806b8456e67e603e')
 ('Audius Network Mainnet', '0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef4892469da293bb661f9')
 ('DODOEX V2', '0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653e234ba5b803746d8f78')
 ('PoolTogether', '0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e22928b1f63ce48fcb40')
 ('mStable Protocol', '0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfdb49b205e14247374947')
 ('PoolTogether', '0xbae01a063ad846d7e4200757480544b5feb1f0217d94db1db97b48bb7f124dbf')
 ('PoolTogether', '0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a')
 (nan, '0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f68ed4c74964ae705cbd')
 ('RAI Mainnet', '0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94922249096e4c9a191c7')
 (nan, '0xf8481d0118ec6098d00629414d600f5d87a1c8a94e2720933643d2eacf648311')] [3.39663580e-01 4.11581522e-01 3.92069305e-01 4.92078917e-01
 0.00000000e+00 3.78817647e-01 4.82708614e+01 4.22866405e-01
 8.87278014e+02 3.38503468e-01 6.90649189e+00 2.61795423e-01
 0.00000000e+00 4.01530683e-02 0.00000000e+00]

Indexing Reward Weekly per Subgraph:
[('Opyn Gamma Mainnet', '0x014e8a3184d5fad198123419a7b54d5f7c9f8a981116462591fbb1a922c39811')
 ('UMA Mainnet Voting', '0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996238adc2bfd396b5f715')
 ('PoolTogether', '0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500')
 ('Omen', '0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e97a1402795c0c2fa99b')
 (nan, '0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e74b6186d3a2264588fe5')
 ('PoolTogether v3_1_0', '0x4a008334f8e7ea21be223d15462084f51abcc0e6625f61de806b8456e67e603e')
 ('Audius Network Mainnet', '0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef4892469da293bb661f9')
 ('DODOEX V2', '0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653e234ba5b803746d8f78')
 ('PoolTogether', '0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e22928b1f63ce48fcb40')
 ('mStable Protocol', '0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfdb49b205e14247374947')
 ('PoolTogether', '0xbae01a063ad846d7e4200757480544b5feb1f0217d94db1db97b48bb7f124dbf')
 ('PoolTogether', '0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a')
 (nan, '0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f68ed4c74964ae705cbd')
 ('RAI Mainnet', '0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94922249096e4c9a191c7')
 (nan, '0xf8481d0118ec6098d00629414d600f5d87a1c8a94e2720933643d2eacf648311')] [2.37764424e+00 2.88106966e+00 2.74448419e+00 3.44455124e+00
 0.00000000e+00 2.65172262e+00 3.37895914e+02 2.96006382e+00
 6.21094396e+03 2.36952346e+00 4.83454266e+01 1.83256733e+00
 0.00000000e+00 2.81071381e-01 0.00000000e+00]

Indexing Reward Yearly per Subgraph:
[('Opyn Gamma Mainnet', '0x014e8a3184d5fad198123419a7b54d5f7c9f8a981116462591fbb1a922c39811')
 ('UMA Mainnet Voting', '0x2aaeb45afa62af1cc8f6d61decd5249429e0aaed67996238adc2bfd396b5f715')
 ('PoolTogether', '0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500')
 ('Omen', '0x31f6fb67c823a07a93bae6b022798eebdf86210033c0e97a1402795c0c2fa99b')
 (nan, '0x4810cc7741423cec7e44fc7ec7a479e521453cbf090e74b6186d3a2264588fe5')
 ('PoolTogether v3_1_0', '0x4a008334f8e7ea21be223d15462084f51abcc0e6625f61de806b8456e67e603e')
 ('Audius Network Mainnet', '0x500a8e47cbdeca7386448ae9e7d52578871b9942ebbef4892469da293bb661f9')
 ('DODOEX V2', '0x5e48ee6773576d45a38934cb19780b5c8c75f8c36e653e234ba5b803746d8f78')
 ('PoolTogether', '0x666d78959706d7e1ed20befeb1d2c9a4e512a22931d8e22928b1f63ce48fcb40')
 ('mStable Protocol', '0xa7d9d3a173d3d62ce3d05c2d29f3447b04edc248cbcfdb49b205e14247374947')
 ('PoolTogether', '0xbae01a063ad846d7e4200757480544b5feb1f0217d94db1db97b48bb7f124dbf')
 ('PoolTogether', '0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a')
 (nan, '0xc064c354bc21dd958b1d41b67b8ef161b75d2246b425f68ed4c74964ae705cbd')
 ('RAI Mainnet', '0xc420d79a888eb0e34203bfeca1048d35f9763b9880a94922249096e4c9a191c7')
 (nan, '0xf8481d0118ec6098d00629414d600f5d87a1c8a94e2720933643d2eacf648311')] [1.23977269e+02 1.50227331e+02 1.43105369e+02 1.79608895e+02
 0.00000000e+00 1.38268511e+02 1.76188733e+04 1.54346316e+02
 3.23856638e+05 1.23553828e+02 2.52087081e+03 9.55553775e+01
 0.00000000e+00 1.46558773e+01 0.00000000e+00]

TOTAL Indexind Reward Daily/Weekly/Yearly
945.5328962579483
6618.728000261518
345119.68106027634


Optimize Allocations:
==============================

Optimize Allocations for Interval: indexingRewardDay and Percentage per Allocation: 0.9
1 Set Declarations
    x_index : Size=1, Index=None, Ordered=False
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/misc.py", line 176, in sorted_robust
    return sorted(arg)
TypeError: '<' not supported between instances of 'float' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./allocation_script.py", line 559, in <module>
    model.pprint()
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/component.py", line 500, in pprint
    self._pprint_base_impl(
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/component.py", line 370, in _pprint_base_impl
    _fcn(ostream, _key, _data_dict[_key])
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/block.py", line 1998, in _pprint_callback
    data._pprint_blockdata_components(ostream)
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/block.py", line 1702, in _pprint_blockdata_components
    self.component(key).pprint(ostream=indented_ostream)
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/component.py", line 500, in pprint
    self._pprint_base_impl(
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/component.py", line 363, in _pprint_base_impl
    tabular_writer( ostream, '', _data, _header, _fcn )
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/misc.py", line 221, in tabular_writer
    _rowSet = row_generator(_key, _val)
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/set.py", line 2205, in <lambda>
    Set._pprint_members(v),
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/set.py", line 2128, in _pprint_members
    return '{' + str(x.ordered_data())[1:-1] + "}"
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/set.py", line 1180, in ordered_data
    return self.sorted_data()
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/set.py", line 1177, in sorted_data
    return tuple(sorted_robust(self.data()))
  File "/usr/local/lib/python3.8/dist-packages/pyomo/core/base/misc.py", line 178, in sorted_robust
    return sorted(arg, key=_robust_sort_keyfcn())
TypeError: '<' not supported between instances of 'float' and 'str'

```
Also i find out that everything works on commit ```8d16b860c65a32dcf6c7d9456108443207086733```

**Comment by CaronSch** [comment]
Hey SpontaneousOverthrow,
We're aware of this issue and will be pushing a fix soon. It has to do with the no-subgraph-list feature. Something about the meta subgraph was changed and it broke that part of our script. I recommend you run the script with the --subgraph-list param instead. We also stick to just 1 parallel allocation ourselves. Let me know if that works for you.

**Comment by SpontaneousOverthrow** [comment]
thanks!
```python3 ./allocation_script.py --indexer_id 0x453b5e165cf98ff60167ccd3560ebf8d436ca86c --max_percentage 0.9 --threshold 20 --parallel_allocations 1 --subgraph-list
``` that's work

**Comment by CaronSch** [comment]
Great! I'm glad i could help out
