### ISSUE TITLE
Error running streamlit run app.py

### ISSUE THREAD

**Issue by bleiva** [anyblockanalytics/thegraph-allocation-optimization#5]
Hi guys, I have another error when I try to run streamlit:

```
(env) [bleiva@fedora34 thegraph-allocation-optimization (main ✗)]$ streamlit run app.py


  👋 Welcome to Streamlit!

  If you're one of our development partners or you're interested in getting
  personal technical support or Streamlit updates, please enter your email
  address below. Otherwise, you may leave the field blank.

  Email:

  Privacy Policy:
  As an open source project, we collect usage statistics. We cannot see and do
  not store information contained in Streamlit apps. You can find out more by
  reading our privacy policy at: https://streamlit.io/privacy-policy

  If you'd like to opt out of usage statistics, add the following to
  ~/.streamlit/config.toml, creating that file if necessary:

    [browser]
    gatherUsageStats = false


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.137:8501

2021-10-05 15:59:51.123 Traceback (most recent call last):
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 509, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 308, in _read_from_cache
    raise e
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 293, in _read_from_cache
    return _read_from_mem_cache(
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 212, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/app.py", line 7, in <module>
    streamlitEntry()
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/src/webapp/overview.py", line 28, in streamlitEntry
    df_closed = getClosedAllocationPerformance(indexer_id)
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 543, in wrapped_func
    return get_or_create_cached_value()
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/env/lib64/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 527, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/src/webapp/key_metrics.py", line 53, in getClosedAllocationPerformance
    df = calculateRewardsAllClosedAllocations(indexer_id)
  File "/home/bleiva/Repos/Protofire/thegraph-allocation-optimization/src/performance_tracking.py", line 219, in calculateRewardsAllClosedAllocations
    reward_rate_day = (int(allocation.get('indexingRewards')) / 10 ** 18) / (
ZeroDivisionError: float division by zero

```

**Comment by enderYm** [comment]
Hi! Could you please checkout the developer branch and test it there again? This could be related to a bug that is already fixed. If it doesn't work there, could you post the error message which is returned from the developer branch?
